/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingProgramRouteImport } from './routes/wedding-program'
import { Route as PhotographyScheduleRouteImport } from './routes/photography-schedule'
import { Route as IndexRouteImport } from './routes/index'

const WeddingProgramRoute = WeddingProgramRouteImport.update({
  id: '/wedding-program',
  path: '/wedding-program',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyScheduleRoute = PhotographyScheduleRouteImport.update({
  id: '/photography-schedule',
  path: '/photography-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/photography-schedule': typeof PhotographyScheduleRoute
  '/wedding-program': typeof WeddingProgramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/photography-schedule': typeof PhotographyScheduleRoute
  '/wedding-program': typeof WeddingProgramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/photography-schedule': typeof PhotographyScheduleRoute
  '/wedding-program': typeof WeddingProgramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/photography-schedule' | '/wedding-program'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/photography-schedule' | '/wedding-program'
  id: '__root__' | '/' | '/photography-schedule' | '/wedding-program'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PhotographyScheduleRoute: typeof PhotographyScheduleRoute
  WeddingProgramRoute: typeof WeddingProgramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedding-program': {
      id: '/wedding-program'
      path: '/wedding-program'
      fullPath: '/wedding-program'
      preLoaderRoute: typeof WeddingProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography-schedule': {
      id: '/photography-schedule'
      path: '/photography-schedule'
      fullPath: '/photography-schedule'
      preLoaderRoute: typeof PhotographyScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PhotographyScheduleRoute: PhotographyScheduleRoute,
  WeddingProgramRoute: WeddingProgramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
