/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingProgramRouteImport } from './routes/wedding-program'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as PhotographyScheduleRouteImport } from './routes/photography-schedule'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'

const WeddingProgramRoute = WeddingProgramRouteImport.update({
  id: '/wedding-program',
  path: '/wedding-program',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyScheduleRoute = PhotographyScheduleRouteImport.update({
  id: '/photography-schedule',
  path: '/photography-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/photography-schedule': typeof PhotographyScheduleRoute
  '/reception': typeof ReceptionRoute
  '/wedding-program': typeof WeddingProgramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/photography-schedule': typeof PhotographyScheduleRoute
  '/reception': typeof ReceptionRoute
  '/wedding-program': typeof WeddingProgramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/photography-schedule': typeof PhotographyScheduleRoute
  '/reception': typeof ReceptionRoute
  '/wedding-program': typeof WeddingProgramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/photography-schedule'
    | '/reception'
    | '/wedding-program'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/photography-schedule'
    | '/reception'
    | '/wedding-program'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/photography-schedule'
    | '/reception'
    | '/wedding-program'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  PhotographyScheduleRoute: typeof PhotographyScheduleRoute
  ReceptionRoute: typeof ReceptionRoute
  WeddingProgramRoute: typeof WeddingProgramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedding-program': {
      id: '/wedding-program'
      path: '/wedding-program'
      fullPath: '/wedding-program'
      preLoaderRoute: typeof WeddingProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography-schedule': {
      id: '/photography-schedule'
      path: '/photography-schedule'
      fullPath: '/photography-schedule'
      preLoaderRoute: typeof PhotographyScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  PhotographyScheduleRoute: PhotographyScheduleRoute,
  ReceptionRoute: ReceptionRoute,
  WeddingProgramRoute: WeddingProgramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
