/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhotographyScheduleRouteImport } from './routes/photography-schedule'
import { Route as OrderOfServiceRouteImport } from './routes/order-of-service'
import { Route as IndexRouteImport } from './routes/index'

const PhotographyScheduleRoute = PhotographyScheduleRouteImport.update({
  id: '/photography-schedule',
  path: '/photography-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOfServiceRoute = OrderOfServiceRouteImport.update({
  id: '/order-of-service',
  path: '/order-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/order-of-service': typeof OrderOfServiceRoute
  '/photography-schedule': typeof PhotographyScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/order-of-service': typeof OrderOfServiceRoute
  '/photography-schedule': typeof PhotographyScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/order-of-service': typeof OrderOfServiceRoute
  '/photography-schedule': typeof PhotographyScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/order-of-service' | '/photography-schedule'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/order-of-service' | '/photography-schedule'
  id: '__root__' | '/' | '/order-of-service' | '/photography-schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrderOfServiceRoute: typeof OrderOfServiceRoute
  PhotographyScheduleRoute: typeof PhotographyScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/photography-schedule': {
      id: '/photography-schedule'
      path: '/photography-schedule'
      fullPath: '/photography-schedule'
      preLoaderRoute: typeof PhotographyScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-of-service': {
      id: '/order-of-service'
      path: '/order-of-service'
      fullPath: '/order-of-service'
      preLoaderRoute: typeof OrderOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrderOfServiceRoute: OrderOfServiceRoute,
  PhotographyScheduleRoute: PhotographyScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
